# Generated by Django 5.1.4 on 2024-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Company Name')),
                ('industry', models.CharField(choices=[('M', 'Manufacturing'), ('F', 'Finance'), ('O', 'Other')], max_length=100, verbose_name='Industry')),
            ],
        ),
    ]
